Add runbook
Financial-Times/neo4j-metric-aggregator pull request #7
Opened 2020-08-24 13:21 UTC by mchompalova

# Description

Add runbook for the service.

## Why

https://financialtimes.atlassian.net/browse/UPPSF-1181

## Scope and particulars of this PR (Please tick all that apply)

- [ ] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [ ] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2020-08-24 13:30 UTC, bboykov approved these changes

2020-08-25 09:48 UTC, bboykov approved these changes

2020-08-25 10:03 UTC, karsov requested changes
The description field is not accurate. My comment on the "Architecture" is only a suggestion.

2020-08-25 10:03 UTC, karsov commented on runbooks/runbook.md
> +To get the metrics for a particular concept, use the following command:
I would write here that the service calculates the number of annotations for a concept and leave the query details for the README.

2020-09-02 11:55 UTC, karsov approved these changes

2020-09-02 12:46 UTC, mihaylovmihail approved these changes

2020-09-02 12:49 UTC, merged